[package]
name = "host"
version = "0.1.0"
edition = "2021"

[dependencies]
methods = { path = "../methods" }
risc0-zkvm = { version = "^3.0.1" }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
serde = "1.0"
base64 = "0.22.1"
bincode = "1"
ogzkp-core = { path = "../core" }
bitcoin = "0.32.7"
