// These constants represent the RISC-V ELF and the image ID generated by risc0-build.
// The ELF is used for proving and the ID is used for verification.
use methods::{OGZKP_ELF, OGZKP_ID};
use risc0_zkvm::{default_prover, ExecutorEnv, ProverOpts, Receipt, ReceiptKind};

use ogzkp_core::{
    generate_header_merkle_proof, headers_merkle_root, recover_pubkey_from_bitcoin_signed_message,
};

use bitcoin::{Address, Network};

use base64::prelude::*;
use bincode;
use bitcoin::bech32;
use bitcoin::bech32::{Bech32m, Hrp};
use flate2::{bufread::GzDecoder, write::GzEncoder, Compression};
use serde::Deserialize;
use std::io::{Read, Write};

use bitcoin::consensus;
use bitcoin::hashes::Hash as _;
use bitcoin::MerkleBlock;

#[derive(Deserialize)]
struct TxShort {
    txid: String,
}

const MEMPOOL_API: &str = "https://mempool.space/api";

async fn fetch_txids(
    endpoint: &str,
    address: &str,
    after_txid: Option<&str>,
) -> Result<Vec<String>, reqwest::Error> {
    // Build the URL
    let mut url = format!("{}/address/{}/txs", endpoint, address);
    if let Some(cursor) = after_txid {
        url.push_str(&format!("?after_txid={}", cursor));
    }

    // Send the request
    let client = reqwest::Client::new();
    let resp = client
        .get(url)
        .header("accept", "application/json")
        .send()
        .await?
        .error_for_status()?;

    // Parse the response
    let txs: Vec<TxShort> = resp.json().await?;

    // Return the txids
    Ok(txs.into_iter().map(|t| t.txid).collect())
}

async fn find_first_seen_txid(
    endpoint: &str,
    address: &str,
) -> Result<Option<String>, reqwest::Error> {
    // Walk pages using the second-to-last txid as the cursor until only one remains
    let mut after_txid = None;
    loop {
        let txids = fetch_txids(endpoint, address, after_txid.as_deref()).await?;

        // If no txids, return None
        if txids.is_empty() {
            return Ok(None);
        }

        // If there's only one txid, we have the first seen tx
        if txids.len() == 1 {
            return Ok(Some(txids[0].clone()));
        }

        // Set the cursor to the second-to-last txid
        let next_txid = Some(txids[txids.len() - 2].clone());
        if next_txid == after_txid {
            panic!("This instance of the mempool API does not support pagination");
        }
        after_txid = next_txid;
    }
}

async fn fetch_spv_proof(endpoint: &str, txid: &str) -> Result<String, reqwest::Error> {
    let client = reqwest::Client::new();
    let url = format!("{}/tx/{}/merkleblock-proof", endpoint, txid);
    let resp = client.get(url).send().await?;
    let proof: String = resp.text().await?;
    Ok(proof)
}

async fn fetch_raw_tx(endpoint: &str, txid: &str) -> Result<String, reqwest::Error> {
    let client = reqwest::Client::new();
    let url = format!("{}/tx/{}/hex", endpoint, txid);
    let resp = client.get(url).send().await?;
    let tx: String = resp.text().await?;
    Ok(tx)
}

fn serialize_receipt(receipt: &Receipt) -> String {
    let receipt_bytes = bincode::serialize(receipt).unwrap();
    let mut encoder = GzEncoder::new(Vec::new(), Compression::default());
    encoder.write_all(&receipt_bytes).unwrap();
    let compressed = encoder.finish().unwrap();
    let hrp = Hrp::parse("ogzkp").unwrap();
    bech32::encode::<Bech32m>(hrp, &compressed).unwrap()
}

fn deserialize_receipt(receipt: &str) -> Receipt {
    let (_hrp, compressed) = bech32::decode(receipt).unwrap();
    let mut decoder = GzDecoder::new(&compressed[..]);
    let mut decompressed = Vec::new();
    decoder.read_to_end(&mut decompressed).unwrap();
    bincode::deserialize(&decompressed).unwrap()
}

#[tokio::main]
async fn main() {
    println!("og-zkp");

    // User input
    // 1LukeQU5jwebXbMLDVydeH4vFSobRV9rkj
    let message = "og-zkp x.com/lukechilds";
    let signature =
        "HE6QfyPFmJvCGjWohZYAVa+pbdSRjeQpdNbXp6zNbDCnEN65xmK+WYidKlt6J1E/GDJpmLcatjEazVo5wqOg6wM=";
    println!();
    println!("Inputs");
    println!("message: {}", message);
    println!("signature: {}", signature);

    // Decode the base64 signature
    let signature_bytes = BASE64_STANDARD.decode(signature).unwrap();

    // Recover pubkey from the signed message
    let pubkey = recover_pubkey_from_bitcoin_signed_message(&signature_bytes, &message)
        .expect("Failed to recover pubkey from bitcoin signed message");

    // Derive P2PKH address from pubkey
    let address = Address::p2pkh(&pubkey, Network::Bitcoin);
    println!("Extracted P2PKH address: {}", address);

    // Lookup first-seen txid for this address
    println!("Looking up first-seen txid for address...");
    let txid = match find_first_seen_txid(MEMPOOL_API, &address.to_string()).await {
        Ok(Some(txid)) => txid,
        Ok(None) => {
            println!("No transactions found for address! Exiting...");
            return;
        }
        Err(e) => {
            eprintln!("Failed to fetch transactions: {}", e);
            return;
        }
    };
    println!("First seen txid: {}", txid);

    println!("Fetching raw tx...");
    let tx = fetch_raw_tx(MEMPOOL_API, &txid).await.unwrap();

    println!("Fetching transaction inclusion proof...");
    let spv_proof = fetch_spv_proof(MEMPOOL_API, &txid).await.unwrap();

    println!("Generating block inclusion proof...");
    let spv_proof_bytes = hex::decode(&spv_proof).unwrap();
    let merkle_block: MerkleBlock = consensus::encode::deserialize(&spv_proof_bytes).unwrap();
    let block_hash = merkle_block.header.block_hash().to_byte_array();
    let header_proof =
        generate_header_merkle_proof(block_hash).expect("Header not found in known header set");
    let block_inclusion_root = headers_merkle_root();

    // Bundle input
    let input = (
        message,
        signature_bytes,
        tx,
        spv_proof,
        header_proof,
        block_inclusion_root,
    );
    let env = ExecutorEnv::builder()
        .write(&input)
        .unwrap()
        .build()
        .unwrap();

    // Prove the program and obtain the receipt.
    println!("Proving...");
    let prover = default_prover();
    let opts = ProverOpts::default().with_receipt_kind(ReceiptKind::Groth16);
    let receipt = prover
        .prove_with_opts(env, OGZKP_ELF, &opts)
        .unwrap()
        .receipt;

    // Serialize the receipt and print as bech32m
    let serialized_receipt = serialize_receipt(&receipt);
    println!();
    println!("Receipt");
    println!("{}", serialized_receipt);

    // Verify correct data commitments in the receipt journal.
    let (block_inclusion_root, block_month, identity): ([u8; 32], String, String) =
        receipt.journal.decode().unwrap();
    println!();
    println!(
        "Block inclusion root: {:?}",
        hex::encode(block_inclusion_root)
    );
    println!("Block month: {:?}", block_month);
    println!("Identity: {:?}", identity);
    println!();

    // The receipt was verified at the end of proving, but the below code is an
    // example of how someone else could verify this receipt.
    deserialize_receipt(&serialized_receipt)
        .verify(OGZKP_ID)
        .unwrap();
}
