// These constants represent the RISC-V ELF and the image ID generated by risc0-build.
// The ELF is used for proving and the ID is used for verification.
use methods::{OGZKP_ELF, OGZKP_ID};
use risc0_zkvm::{default_prover, ExecutorEnv, ProverOpts, ReceiptKind};

use base64::prelude::*;
use bincode;

fn main() {
    // Initialize tracing. In order to view logs, run `RUST_LOG=info cargo run`
    tracing_subscriber::fmt()
        .with_env_filter(tracing_subscriber::filter::EnvFilter::from_default_env())
        .init();

    println!("og-zkp");

    // User input
    // 1LukeQU5jwebXbMLDVydeH4vFSobRV9rkj
    let message = "og-zkp x.com/lukechilds";
    let signature =
        "HE6QfyPFmJvCGjWohZYAVa+pbdSRjeQpdNbXp6zNbDCnEN65xmK+WYidKlt6J1E/GDJpmLcatjEazVo5wqOg6wM=";
    println!();
    println!("Inputs");
    println!("message: {}", message);
    println!("signature: {}", signature);

    // Create an executor environment and pass in the input.
    let signature_bytes = BASE64_STANDARD.decode(signature).unwrap();
    let input = (message, signature_bytes);
    let env = ExecutorEnv::builder()
        .write(&input)
        .unwrap()
        .build()
        .unwrap();

    // Prove the program and obtain the receipt.
    let prover = default_prover();
    let opts = ProverOpts::default().with_receipt_kind(ReceiptKind::Groth16);
    let receipt = prover
        .prove_with_opts(env, OGZKP_ELF, &opts)
        .unwrap()
        .receipt;

    // Serialize the receipt and print as base64
    let receipt_bytes = bincode::serialize(&receipt).unwrap();
    let receipt_b64 = BASE64_STANDARD.encode(receipt_bytes);
    println!();
    println!("Receipt");
    println!("{}", receipt_b64);

    // Verify correct data commitments in the receipt journal.
    let receipt_output: String = receipt.journal.decode().unwrap();
    println!();
    println!("Commitment: {:?}", receipt_output);

    // The receipt was verified at the end of proving, but the below code is an
    // example of how someone else could verify this receipt.
    receipt.verify(OGZKP_ID).unwrap();
}
