name: CI

on: push

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - name: Free disk space
        run: sudo rm -rf /usr/local/lib/android /usr/share/dotnet /opt/ghc /usr/local/share/boost

      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-

      - name: Install RISC Zero toolchain (rzup)
        run: |
          curl -L https://risczero.com/install | bash
          echo "$HOME/.risc0/bin" >> $GITHUB_PATH
          ~/.risc0/bin/rzup install rust 1.88.0
          ~/.risc0/bin/rzup install cpp 2024.1.5

      - name: Run unit tests
        run: cargo test --workspace --lib --bin og-zkp

  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-

      - name: Install RISC Zero toolchain (rzup)
        run: |
          curl -L https://risczero.com/install | bash
          echo "$HOME/.risc0/bin" >> $GITHUB_PATH
          ~/.risc0/bin/rzup install rust 1.88.0
          ~/.risc0/bin/rzup install cpp 2024.1.5

      - name: Run e2e tests
        run: cargo test --test e2e

  e2e-fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-

      - name: Install RISC Zero toolchain (rzup)
        run: |
          curl -L https://risczero.com/install | bash
          echo "$HOME/.risc0/bin" >> $GITHUB_PATH
          ~/.risc0/bin/rzup install rust 1.88.0
          ~/.risc0/bin/rzup install cpp 2024.1.5

      - name: Run e2e tests
        run: OG_ZKP_TEST_MEMPOOL_LOOKUP="1" cargo test --test e2e
