name: CI

on: push

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run e2e tests
        run: cargo test --test e2e

  e2e-offline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run e2e tests
        run: OGZKP_TEST_OFFLINE_MODE="1" cargo test --test e2e
